// <auto-generated />
using System;
using CityWasp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityWasp.Migrations
{
    [DbContext(typeof(CityWaspContext))]
    partial class CityWaspContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CityWasp.Models.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("coordinates")
                        .HasColumnType("text");

                    b.Property<decimal>("currentValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("mileage")
                        .HasColumnType("text");

                    b.Property<string>("model")
                        .HasColumnType("text");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.Property<DateTime>("techincal")
                        .HasColumnType("datetime");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("CityWasp.Models.Discount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime");

                    b.Property<int>("percent")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("CityWasp.Models.Trip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<int>("discountApplied")
                        .HasColumnType("int");

                    b.Property<int>("distance")
                        .HasColumnType("int");

                    b.Property<int>("length")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("CityWasp.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
